[package]
name    = "horizon_math"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name       = "horizon_math"
crate-type = ["staticlib"]

[profile.release]
opt-level        = "z"
lto              = "fat"
codegen-units    = 1
panic            = "abort"
strip            = "symbols"
overflow-checks  = false
debug            = false
incremental      = false

[profile.release.package."*"]
opt-level = "z"
